### ISSUE TITLE
structured variables in strings are not highlighted

### ISSUE THREAD

**Issue by genebean** [lingua-pupuli/puppet-editor-syntax#16]
### What Versions are you running?
0.13.2

Editor Name and Version: VS Code 1.28.2 (1.28.2)
Theme: n/a
Document:

```puppet
$facts['os']['family']
$foo = "Random bar ${unstructured} ${facts['kernel']}"
```

![image](https://user-images.githubusercontent.com/966789/47792725-0131ba80-dcf3-11e8-94c8-c37d3b9c55a1.png)

### What You Are Seeing?

In the above example you can see that `${unstructured}` is properly highlighted while `${facts['kernel']}` is not. This happens with any kind of hash variable in a string (not just facts)

### What is Expected?

All variables are highlighted the same

**Comment by glennsarti** [comment]
Ok...string interpolation is broken.

**Comment by glennsarti** [comment]
This will be a little tricky as the current file is basically hardcoded for variables in ${...} only :-(
