### ISSUE TITLE
Apostrophe in heredoc breaks highlighting

### ISSUE THREAD

**Issue by genebean** [lingua-pupuli/puppet-editor-syntax#22]
### What Versions are you running?

Editor Name and Version: 
- VS Code 1.29.1
- plugin 0.13.2

Document: (Include the whole document)

```puppet
class foo {
  profile::notes { $title:
    notes => @("NOTES"),
      A note with an apostrophe in it's midst breaks
      highlighting.
      |-NOTES
  }
  
  include blah
  
  file { 'some-file':
    ensure => 'present'
  }
}
```

### What You Are Seeing?

When an apostrophe is included in a heredoc it breaks highlighting as shown here:

![heredoc-with-apostrophe](https://user-images.githubusercontent.com/966789/49022878-f1778b80-f163-11e8-8c7c-e57e48cf541d.png)

### What is Expected?

Proper highlighting like show here when the apostrophe has been removed:

![heredoc-without-apostrophe](https://user-images.githubusercontent.com/966789/49022925-09e7a600-f164-11e8-99ea-4c365e7d9d01.png)
 

### How Did You Get This To Happen? (Steps to Reproduce)

Add an apostrophe to a heredoc as shown in the sample code above.

**Comment by glennsarti** [comment]
Heredoc specification;
https://github.com/puppetlabs/puppet-specifications/blob/master/language/heredoc.md

**Comment by glennsarti** [comment]
and https://puppet.com/docs/puppet/6.0/lang_data_string.html#heredocs

**Comment by glennsarti** [comment]
@genebean PR #23 is up, looks like it'll fix your issue.
