### ISSUE TITLE
Regex Capture Variables not highlighted, interfere with other highlighting as well

### ISSUE THREAD

**Issue by philomory** [lingua-pupuli/puppet-editor-syntax#30]
Regex Capture Variables such as `$1` are both not highlighted correctly themselves, and also interfere with other highlighting, for example resource highlighting. For example, given the following code:

```
example_resource { $foo:
  bar => $baz,
}

if $string =~ /(.+)pattern(.+)/ {
  example_resource { $1:
    bar => $2,
  }
}
```
The highlighting looks like this: 
![image](https://user-images.githubusercontent.com/200123/56258132-37c57c80-606a-11e9-958c-c511b46f38b9.png)

Note both that the `$2` does not highlight the way a normal variable does (compare `$baz`), and also that the presence of `$1` as the resource title prevents `example_resource` from highlighting properly as well.

Other places where variables are highlighted (such as `"${1}"`) are affected as well. Overall it seems as if `$1` is just not detected as a valid variable token at all.

### What Versions are you running?

Editor Name and Version: Visual Studio Code 1.33.1
Plugin Version: jpogran.puppet-vscode 0.18.0
Theme: nkjoep.mac-classic-theme

**Comment by glennsarti** [comment]
Thanks @philomory .  Yep, those are valid variable names according to https://puppet.com/docs/puppet/5.4/lang_reserved.html#regular-expressions-for-variable-names .  I suspect the syntax thinks they're numbers not variable names.  This will be fixed in the next release.
