### ISSUE TITLE
Comment inside a hash inside an array, not recognized as such

### ISSUE THREAD

**Issue by philomory** [lingua-pupuli/puppet-editor-syntax#34]
![image](https://user-images.githubusercontent.com/200123/57814494-7bfe7800-770f-11e9-8c79-a2bc87818560.png)

### What Versions are you running?

Editor Name and Version: Visual Studio Code 1.33.1 with Puppet plugin 0.18.0
Theme: Mac Classic
Document:
```puppet
$x1 = {
  parent => {
    key1 => 'value',
    # comment here is ok
    key2 => 'value',
  },
}

$x2 = {
  parent => [
    'value',
    # comment here is ok
    'value',
  ],
}

$x3 = [
  [
    'value',
    # comment here is ok
    'value',
  ],
]

$x4 = [
  {
    key1 => 'value',
    # comment here does not work
    key2 => 'value',
  },
]
```

### What You Are Seeing?
Comments should be recognized as such, even when inside a hash inside an array.

### What is Expected?
Comments are not recognized as such if they appear inside a hash inside an array.

### How Did You Get This To Happen? (Steps to Reproduce)
Put a hash inside an array, then try to include comments.

Note that although the example shows comments on their own lines, this also applies to comments on the same line as hash value (but not _inside_ the hash value, if the hash value itself is another array).

**Comment by glennsarti** [comment]
@philomory Thanks for the issue report.  It's fixed and will be released in the next Puppet Extension release.
