### ISSUE TITLE
code completion for notify should not have ensure

### ISSUE THREAD

**Issue by TJM** [lingua-pupuli/puppet-editor-syntax#5]
### What Versions are you running?

Editor Name and Version: VSCode 1.26.1
Theme: (dark?)
Document: test.pp

### What You Are Seeing?
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'ensure' (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/test.pp, line: 106) on Notify[testing] 

### What is Expected?
the message I tried to notify out

### How Did You Get This To Happen? (Steps to Reproduce)

in a puppet file type "notify" and hit "tab" when the code completion dialog comes up... resulting output is:

```
notify { 'title':
  ensure => 'present'
}
```

The "ensure" parameter is not valid.

**Comment by glennsarti** [comment]
This is a bug in the Puppet Editor Services.  Being tracked in https://github.com/lingua-pupuli/puppet-editor-services/issues/67.  For now I'm closing this issue.
