### ISSUE TITLE
Variables are wrongly assumed to be always in snake_case

### ISSUE THREAD

**Issue by Zezombye** [lingua-pupuli/puppet-editor-syntax#52]
Document: 
```
$foo = 1
$fooBar = 2
```

### What You Are Seeing?

![](https://i.imgur.com/yuOEpCj.png)

The syntax coloration does not support camelCase for variables.

### What is Expected?

camelCase is supported for variables.

### How Did You Get This To Happen? (Steps to Reproduce)

Copy paste the document in a file

**Comment by jpogran** [comment]
Thanks for the bug report. The syntax grammar works like that because we use the recommended Puppet style guide for variable naming https://puppet.com/docs/puppet/5.5/style_guide_variables.html#variable-format

**Comment by Zezombye** [comment]
Sure, though IMO syntax colorators shouldn't force a style guide, but instead follow puppet's own grammar (which does allow camelcase). To my knowledge, no other syntax colorator does this: I can have camelcase in python, or snakecase in java, and they still are colored correctly.

**Comment by Zezombye** [comment]
Thanks for fixing this! However I just found out there is still a minor bug regarding variables in strings:

![](https://i.imgur.com/yKRyRgv.png)
